name: React Reusable CI/CD Pipeline

on:
  workflow_call:

  push:
    branches:
      - development

jobs:

  build-artifact:
    name: Build and Publish React App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Create package.json for Build
        run: |
          echo '{
            "name": "react-app-build",
            "version": "1.0.1",
            "description": "React App Build Artifact",
            "main": "index.js",
            "license": "MIT"
          }' > build/package.json

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws-region }}

      - name: Login to AWS CodeArtifact
        run: |
          aws codeartifact login \
            --tool npm \
            --repository ${{ npm-store }} \
            --domain ${{ ak }} \
            --domain-owner ${{ 897729129103 }}

      - name: Debug .npmrc
        run: cat ~/.npmrc

      - name: Publish Build to AWS CodeArtifact
        working-directory: ./build
        env:
          NPM_REGISTRY_URL: "https://${{ ak }}-${{ 897729129103 }}.d.codeartifact.${{ us-east-1 }}.amazonaws.com/npm/${{ npm-store }}/"
        run: |
          npm set registry $NPM_REGISTRY_URL
          npm publish

      - name: Upload Build Artifact to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: react-app-build
          path: build
